config/routes.rb
CallbackCatcher::Application.routes.draw do
  resources :accesses

end

app/models/access.rb
# == Schema Information
#
# Table name: accesses
#
#  created_at :datetime         not null
#  headers    :text
#  id         :integer          not null, primary key
#  payload    :text
#  updated_at :datetime         not null
#
# Indexes
#
#  index_accesses_on_created_at  (created_at)
#

class Access < ActiveRecord::Base
  attr_accessible :headers, :payload
end

app/controllers/accesses_controller.rb
require 'filter_cookie_values'

class AccessesController < ApplicationController
  skip_before_filter :verify_authenticy_token, :only => [:create]

  # GET /accesses
  # GET /accesses.json
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 10
    @accesses = Access.order("created_at DESC").paginate(page: page, per_page: per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accesses }
    end
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
    @access = Access.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access }
    end
  end

  # GET /accesses/new
  # GET /accesses/new.json
  def new
    create
  end

  # GET /accesses/1/edit
  def edit
    @access = Access.find(params[:id])
  end

  # POST /accesses
  # POST /accesses.json
  def create
    # CGI headers keys start with capital letters
    cgi_headers = request.headers.select {|key, val| key =~ /^[A-Z]/ }

    # filter HTTP_COOKIE values
    filter_cookie_values(cgi_headers, 'HTTP_COOKIE')

    @access = Access.new(headers: JSON.pretty_generate(cgi_headers.to_hash),
                         payload: JSON.pretty_generate(params.to_hash))

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render json: @access, status: :created, location: @access }
      else
        format.html { render action: "new" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accesses/1
  # PUT /accesses/1.json
  def update
    @access = Access.find(params[:id])

    respond_to do |format|
      if @access.update_attributes(params[:access])
        format.html { redirect_to @access, notice: 'Access was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access = Access.find(params[:id])
    @access.destroy

    respond_to do |format|
      format.html { redirect_to accesses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def line_length(str)
    lines = str.split(/\n/)
    lines.push('')		# insure at least one zero length line

    sizes = lines.map(&:size)
    sizes.max
  end

  def num_lines(str)
    str.split(/\n/).size
  end
end

app/views/accesses/_form.html.erb
<%= form_for(@access) do |f| %>
  <% if @access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% @access.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style>
    textarea {
      font-family: monospace;
    }
  </style>

  <%
     textarea_cols = [20, line_length(@access.headers), line_length(@access.payload)].max
     headers_rows = [3, num_lines(@access.headers)].max
     payload_rows = [3, num_lines(@access.payload)].max
  %>

  <div class="field">
    <%= f.label :headers %><br />
    <%= f.text_area :headers, cols: textarea_cols, rows: headers_rows %>
  </div>
  <div class="field">
    <%= f.label :payload %><br />
    <%= f.text_area :payload, cols: textarea_cols, rows: payload_rows %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<h1>Editing access</h1>

<%= render 'form' %>

<%= link_to 'Show', @access %> |
<%= link_to 'Back', accesses_path %>

app/views/accesses/index.html.erb
<h1>Listing accesses</h1>

<%= will_paginate @accesses %>

<table>
  <tr>
    <th>Headers/Payload</th>
    <th>Created At</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accesses.each do |access| %>
  <tr>
    <td>
      <pre><%= access.headers %></pre>
      <pre><%= access.payload %></pre>
    </td>
    <td><%= access.created_at %></td>
    <td><%= link_to 'Show', access %></td>
    <td><%= link_to 'Edit', edit_access_path(access) %></td>
    <td><%= link_to 'Destroy', access, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @accesses %>

app/views/accesses/new.html.erb
<h1>New access</h1>

<%= render 'form' %>

<%= link_to 'Back', accesses_path %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Headers:</b>
  <pre><%= @access.headers %></pre>
</p>

<p>
  <b>Payload:</b>
  <pre><%= @access.payload %></pre>
</p>


<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CallbackCatcher</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>